version: "3"
services:
 node:
  container_name: Manuela
  image: manuelaflores16/orbis-training-docker:4.0.0
  build: .
  ports:
   - 3030:1042
   - 35729:35729
  command: npm start
  volumes:
   - $PWD:/app

 test:
  image: node:10.10.0-slim
  depends_on:
   - node
  command: curl node:1042